public class StringArrayTest{
    
    
        public static list<string> generateStringArray(integer n) {
        
        List<String> ToReturn = new List<String>();
        
        for(integer i=0;i<n;i++  )
        
            {
            
            ToReturn.add( 'Test '+i);
            
            System.Debug(ToReturn);
            
            
        
            }
        return ToReturn;
        
        }
    
    
    
    
    
    }